#include"Question.h"
void setQuestion(Exam myExam[],int QuestionNumber) {
	int number = 0;
	myExam[number].setQuestionText("Grand Central Terminal, Park Avenue, New York is the world's");
	myExam[number].setOptionNumber(4);
	myExam[number].setOption(0, "largest railway station", 1);
	myExam[number].setOption(1, "highest railway station", 0);
	myExam[number].setOption(2, "longest railway station", 0);
	myExam[number].setOption(3, "None of the above", 0);
	number = 1;
	myExam[number].setQuestionText("Entomology is the science that studies");
	myExam[number].setOptionNumber(4);
	myExam[number].setOption(0, "Behavior of human beings", 0);
	myExam[number].setOption(1, "Insects", 1);
	myExam[number].setOption(2, "The origin and history of technical and scientific terms", 0);
	myExam[number].setOption(3, "The formation of rocks", 0);
	number = 2;
	myExam[number].setQuestionText("Eritrea, which became the 182nd member of the UN in 1993, is in the continent of");
	myExam[number].setOptionNumber(4);
	myExam[number].setOption(0, "Asia", 0);
	myExam[number].setOption(1, "Africa", 1);
	myExam[number].setOption(2, "Europe", 0);
	myExam[number].setOption(3, "Australia", 0);
	number = 3;
	myExam[number].setQuestionText("Garampani sanctuary is located at");
	myExam[number].setOptionNumber(4);
	myExam[number].setOption(0, "Junagarh, Gujarat", 0);
	myExam[number].setOption(1, "Diphu, Assam", 1);
	myExam[number].setOption(2, "Kohima, Nagaland", 0);
	myExam[number].setOption(3, "Gangtok, Sikkim", 0);
	number = 4;
	myExam[number].setQuestionText("For which of the following disciplines is Nobel Prize awarded?");
	myExam[number].setOptionNumber(4);
	myExam[number].setOption(0, "Physics and Chemistry", 0);
	myExam[number].setOption(1, "Physiology or Medicine", 0);
	myExam[number].setOption(2, "Literature, Peace and Economics", 0);
	myExam[number].setOption(3, "All of the above", 1);
	number = 5;
	myExam[number].setQuestionText("Hitler party which came into power in 1933 is known as");
	myExam[number].setOptionNumber(4);
	myExam[number].setOption(0, "Labour Party", 0);
	myExam[number].setOption(1, "Nazi Party", 1);
	myExam[number].setOption(2, "Ku-Klux-Klan", 0);
	myExam[number].setOption(3, "Democratic Party", 0);
	number = 6;
	myExam[number].setQuestionText("First human heart transplant operation conducted by Dr. Christiaan Barnard on Louis Washkansky, was conducted in");
	myExam[number].setOptionNumber(4);
	myExam[number].setOption(0, "1967", 1);
	myExam[number].setOption(1, "1968", 0);
	myExam[number].setOption(2, "1958", 0);
	myExam[number].setOption(3, "1922", 0);
	number = 7;
	myExam[number].setQuestionText("Galileo was an Italian astronomer who");
	myExam[number].setOptionNumber(4);
	myExam[number].setOption(0, "developed the telescope", 0);
	myExam[number].setOption(1, "discovered four satellites of Jupiter", 0);
	myExam[number].setOption(2, "discovered that the movement of pendulum produces a regular time measurement", 0);
	myExam[number].setOption(3, "All of the above", 1);
	number = 8;
	myExam[number].setQuestionText("Golf player Vijay Singh belongs to which country ? ");
	myExam[number].setOptionNumber(4);
	myExam[number].setOption(0, "USA", 0);
	myExam[number].setOption(1, "Fiji", 1);
	myExam[number].setOption(2, "India", 0);
	myExam[number].setOption(3, "UK", 0);
	number = 9;
	myExam[number].setQuestionText("First Afghan War took place in ");
	myExam[number].setOptionNumber(4);
	myExam[number].setOption(0, "1839", 1);
	myExam[number].setOption(1, "1843", 0);
	myExam[number].setOption(2, "1833", 0);
	myExam[number].setOption(3, "1848", 0);
}